# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/frane/Work/brokenProxy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/frane/Work/brokenProxy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/frane/Work/brokenProxy/CMakeFiles /home/frane/Work/brokenProxy//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/frane/Work/brokenProxy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named brokenProxy

# Build rule for target.
brokenProxy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 brokenProxy
.PHONY : brokenProxy

# fast build rule for target.
brokenProxy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/build
.PHONY : brokenProxy/fast

lib/cjson/cJSON.o: lib/cjson/cJSON.c.o
.PHONY : lib/cjson/cJSON.o

# target to build an object file
lib/cjson/cJSON.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/lib/cjson/cJSON.c.o
.PHONY : lib/cjson/cJSON.c.o

lib/cjson/cJSON.i: lib/cjson/cJSON.c.i
.PHONY : lib/cjson/cJSON.i

# target to preprocess a source file
lib/cjson/cJSON.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/lib/cjson/cJSON.c.i
.PHONY : lib/cjson/cJSON.c.i

lib/cjson/cJSON.s: lib/cjson/cJSON.c.s
.PHONY : lib/cjson/cJSON.s

# target to generate assembly for a file
lib/cjson/cJSON.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/lib/cjson/cJSON.c.s
.PHONY : lib/cjson/cJSON.c.s

src/Clay/c_mem_debug.o: src/Clay/c_mem_debug.c.o
.PHONY : src/Clay/c_mem_debug.o

# target to build an object file
src/Clay/c_mem_debug.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Clay/c_mem_debug.c.o
.PHONY : src/Clay/c_mem_debug.c.o

src/Clay/c_mem_debug.i: src/Clay/c_mem_debug.c.i
.PHONY : src/Clay/c_mem_debug.i

# target to preprocess a source file
src/Clay/c_mem_debug.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Clay/c_mem_debug.c.i
.PHONY : src/Clay/c_mem_debug.c.i

src/Clay/c_mem_debug.s: src/Clay/c_mem_debug.c.s
.PHONY : src/Clay/c_mem_debug.s

# target to generate assembly for a file
src/Clay/c_mem_debug.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Clay/c_mem_debug.c.s
.PHONY : src/Clay/c_mem_debug.c.s

src/Clay/c_text.o: src/Clay/c_text.c.o
.PHONY : src/Clay/c_text.o

# target to build an object file
src/Clay/c_text.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Clay/c_text.c.o
.PHONY : src/Clay/c_text.c.o

src/Clay/c_text.i: src/Clay/c_text.c.i
.PHONY : src/Clay/c_text.i

# target to preprocess a source file
src/Clay/c_text.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Clay/c_text.c.i
.PHONY : src/Clay/c_text.c.i

src/Clay/c_text.s: src/Clay/c_text.c.s
.PHONY : src/Clay/c_text.s

# target to generate assembly for a file
src/Clay/c_text.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Clay/c_text.c.s
.PHONY : src/Clay/c_text.c.s

src/Europa/e_file.o: src/Europa/e_file.c.o
.PHONY : src/Europa/e_file.o

# target to build an object file
src/Europa/e_file.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Europa/e_file.c.o
.PHONY : src/Europa/e_file.c.o

src/Europa/e_file.i: src/Europa/e_file.c.i
.PHONY : src/Europa/e_file.i

# target to preprocess a source file
src/Europa/e_file.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Europa/e_file.c.i
.PHONY : src/Europa/e_file.c.i

src/Europa/e_file.s: src/Europa/e_file.c.s
.PHONY : src/Europa/e_file.s

# target to generate assembly for a file
src/Europa/e_file.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Europa/e_file.c.s
.PHONY : src/Europa/e_file.c.s

src/Europa/e_threads.o: src/Europa/e_threads.c.o
.PHONY : src/Europa/e_threads.o

# target to build an object file
src/Europa/e_threads.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Europa/e_threads.c.o
.PHONY : src/Europa/e_threads.c.o

src/Europa/e_threads.i: src/Europa/e_threads.c.i
.PHONY : src/Europa/e_threads.i

# target to preprocess a source file
src/Europa/e_threads.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Europa/e_threads.c.i
.PHONY : src/Europa/e_threads.c.i

src/Europa/e_threads.s: src/Europa/e_threads.c.s
.PHONY : src/Europa/e_threads.s

# target to generate assembly for a file
src/Europa/e_threads.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Europa/e_threads.c.s
.PHONY : src/Europa/e_threads.c.s

src/Europa/e_time.o: src/Europa/e_time.c.o
.PHONY : src/Europa/e_time.o

# target to build an object file
src/Europa/e_time.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Europa/e_time.c.o
.PHONY : src/Europa/e_time.c.o

src/Europa/e_time.i: src/Europa/e_time.c.i
.PHONY : src/Europa/e_time.i

# target to preprocess a source file
src/Europa/e_time.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Europa/e_time.c.i
.PHONY : src/Europa/e_time.c.i

src/Europa/e_time.s: src/Europa/e_time.c.s
.PHONY : src/Europa/e_time.s

# target to generate assembly for a file
src/Europa/e_time.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Europa/e_time.c.s
.PHONY : src/Europa/e_time.c.s

src/Styx/s_network.o: src/Styx/s_network.c.o
.PHONY : src/Styx/s_network.o

# target to build an object file
src/Styx/s_network.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Styx/s_network.c.o
.PHONY : src/Styx/s_network.c.o

src/Styx/s_network.i: src/Styx/s_network.c.i
.PHONY : src/Styx/s_network.i

# target to preprocess a source file
src/Styx/s_network.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Styx/s_network.c.i
.PHONY : src/Styx/s_network.c.i

src/Styx/s_network.s: src/Styx/s_network.c.s
.PHONY : src/Styx/s_network.s

# target to generate assembly for a file
src/Styx/s_network.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Styx/s_network.c.s
.PHONY : src/Styx/s_network.c.s

src/Talos/t_error.o: src/Talos/t_error.c.o
.PHONY : src/Talos/t_error.o

# target to build an object file
src/Talos/t_error.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Talos/t_error.c.o
.PHONY : src/Talos/t_error.c.o

src/Talos/t_error.i: src/Talos/t_error.c.i
.PHONY : src/Talos/t_error.i

# target to preprocess a source file
src/Talos/t_error.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Talos/t_error.c.i
.PHONY : src/Talos/t_error.c.i

src/Talos/t_error.s: src/Talos/t_error.c.s
.PHONY : src/Talos/t_error.s

# target to generate assembly for a file
src/Talos/t_error.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/Talos/t_error.c.s
.PHONY : src/Talos/t_error.c.s

src/dnslookup.o: src/dnslookup.c.o
.PHONY : src/dnslookup.o

# target to build an object file
src/dnslookup.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/dnslookup.c.o
.PHONY : src/dnslookup.c.o

src/dnslookup.i: src/dnslookup.c.i
.PHONY : src/dnslookup.i

# target to preprocess a source file
src/dnslookup.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/dnslookup.c.i
.PHONY : src/dnslookup.c.i

src/dnslookup.s: src/dnslookup.c.s
.PHONY : src/dnslookup.s

# target to generate assembly for a file
src/dnslookup.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/dnslookup.c.s
.PHONY : src/dnslookup.c.s

src/main.o: src/main.c.o
.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/main.c.s
.PHONY : src/main.c.s

src/proxy.o: src/proxy.c.o
.PHONY : src/proxy.o

# target to build an object file
src/proxy.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/proxy.c.o
.PHONY : src/proxy.c.o

src/proxy.i: src/proxy.c.i
.PHONY : src/proxy.i

# target to preprocess a source file
src/proxy.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/proxy.c.i
.PHONY : src/proxy.c.i

src/proxy.s: src/proxy.c.s
.PHONY : src/proxy.s

# target to generate assembly for a file
src/proxy.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/proxy.c.s
.PHONY : src/proxy.c.s

src/shared_context.o: src/shared_context.c.o
.PHONY : src/shared_context.o

# target to build an object file
src/shared_context.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/shared_context.c.o
.PHONY : src/shared_context.c.o

src/shared_context.i: src/shared_context.c.i
.PHONY : src/shared_context.i

# target to preprocess a source file
src/shared_context.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/shared_context.c.i
.PHONY : src/shared_context.c.i

src/shared_context.s: src/shared_context.c.s
.PHONY : src/shared_context.s

# target to generate assembly for a file
src/shared_context.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/shared_context.c.s
.PHONY : src/shared_context.c.s

src/traceroute.o: src/traceroute.c.o
.PHONY : src/traceroute.o

# target to build an object file
src/traceroute.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/traceroute.c.o
.PHONY : src/traceroute.c.o

src/traceroute.i: src/traceroute.c.i
.PHONY : src/traceroute.i

# target to preprocess a source file
src/traceroute.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/traceroute.c.i
.PHONY : src/traceroute.c.i

src/traceroute.s: src/traceroute.c.s
.PHONY : src/traceroute.s

# target to generate assembly for a file
src/traceroute.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/brokenProxy.dir/build.make CMakeFiles/brokenProxy.dir/src/traceroute.c.s
.PHONY : src/traceroute.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... brokenProxy"
	@echo "... lib/cjson/cJSON.o"
	@echo "... lib/cjson/cJSON.i"
	@echo "... lib/cjson/cJSON.s"
	@echo "... src/Clay/c_mem_debug.o"
	@echo "... src/Clay/c_mem_debug.i"
	@echo "... src/Clay/c_mem_debug.s"
	@echo "... src/Clay/c_text.o"
	@echo "... src/Clay/c_text.i"
	@echo "... src/Clay/c_text.s"
	@echo "... src/Europa/e_file.o"
	@echo "... src/Europa/e_file.i"
	@echo "... src/Europa/e_file.s"
	@echo "... src/Europa/e_threads.o"
	@echo "... src/Europa/e_threads.i"
	@echo "... src/Europa/e_threads.s"
	@echo "... src/Europa/e_time.o"
	@echo "... src/Europa/e_time.i"
	@echo "... src/Europa/e_time.s"
	@echo "... src/Styx/s_network.o"
	@echo "... src/Styx/s_network.i"
	@echo "... src/Styx/s_network.s"
	@echo "... src/Talos/t_error.o"
	@echo "... src/Talos/t_error.i"
	@echo "... src/Talos/t_error.s"
	@echo "... src/dnslookup.o"
	@echo "... src/dnslookup.i"
	@echo "... src/dnslookup.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/proxy.o"
	@echo "... src/proxy.i"
	@echo "... src/proxy.s"
	@echo "... src/shared_context.o"
	@echo "... src/shared_context.i"
	@echo "... src/shared_context.s"
	@echo "... src/traceroute.o"
	@echo "... src/traceroute.i"
	@echo "... src/traceroute.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

